### ISSUE TITLE
Usage of `_variable`

### ISSUE THREAD

**Issue by sbrinkerhoff** [Jonchun/badlinkfinder#6]
There seems to be quite a few places that underscored variables or attributes are used:

```
    def add_neighbor(self, _from, _to):
        _from = normalize_url(_from)
        _to = normalize_url(_to)
        self._graph.inbound[_to].add(_from)
        self._graph.outbound[_from].add(_to)
```

And for methods

```
    def _smart_crawl(self, url):
        parsed_url = urlparse(url)
```

Is this intentional?

**Comment by jonchun** [comment]
I used _ variables stylistically to indicate that they shouldn't be accessed/called publicly (pseudo-private). In the case of add_neighbor, it was to prevent any confusion with the `from` keyword. I guess I could have just used `from_url` and `to_url` or something else...

Do the underscores cause confusion?

**Comment by sbrinkerhoff** [comment]
If you are looking to hint that the fields are `private` scope, [PEP8](https://www.python.org/dev/peps/pep-0008/) suggests using double underscores for the method name.  The method parameters shouldnt need to be underscored.  It would be more pythonic to not underscore them at all unless absolutely needed.

**Comment by jonchun** [comment]
I was following

> In addition, the following special forms using leading or trailing underscores are recognized (these can generally be combined with any case convention):
> 
> _single_leading_underscore: weak "internal use" indicator. E.g. from M import * does not import objects whose name starts with an underscore.

I can definitely update the prefixed parameters and rename them, but looks like the methods are fine

**Comment by jonchun** [comment]
changed names as part of https://github.com/Jonchun/badlinkfinder/pull/8
